# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmrCGVhs0-zWLflSBtgwBUvt2Ty0F4xx

**PROJECT : 1**

**EDA** - Elploratory Data Azalysis
"""

# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing Data
df = pd.read_csv('retail_sales_dirty_dataset.csv')
df.head()

#Checking Null Values
df.isnull().sum()

#Understanding the data
df.describe(include='all')

#Removing Duplicates
df.drop_duplicates(inplace=True)
df.head()

"""### Handling Missing values

"""

#Separate numeric & categorical columns
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include='object').columns

#Fill numeric columns with median
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

#Fill categorical columns with mode
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

#Fix Date Column
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df.dropna(subset=['Date'], inplace=True)

#Remove Invalid Values
df = df[df['Revenue'] > 0]
df = df[df['Units_Sold'] > 0]

"""### Clean Data Check"""

df.info()

df.isnull().sum()

"""## Exploratory Data Analysis"""

#Sales Distribution
sns.histplot(df['Revenue'], bins=30, kde=True)
plt.title('Sales Distribution')
plt.show()

#Monthly Sales Trend
df['Month'] = df['Date'].dt.month
monthly_sales = df.groupby('Month')['Revenue'].sum()

monthly_sales.plot(kind='bar')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.show()

# Sales by Category
sns.barplot(x='Product_Category', y='Revenue', data=df)
plt.xticks(rotation=45)
plt.title('Sales by Category')
plt.show()

# Top 10 Products by Sales
top_products = df.groupby('Product_Category')['Revenue'].sum().sort_values(ascending=False).head(10)

top_products.plot(kind='bar')
plt.title('Top 10 Products by Sales')
plt.show()

# Correlation
sns.heatmap(df[num_cols].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""## INSIGHTS:
1. Sales are unevenly distributed, with few products contributing most revenue.
2. Certain months show higher sales indicating seasonality.
3. Product category significantly impacts total sales.
"""

